### ISSUE TITLE
Unable to setup integration

### ISSUE THREAD

**Issue by monsterciattolo** [anotherjulien/MyHOME#14]
Hi,
i updated plugin to latest version 0.7.7 but i cannot setup again and i got this error.

Logger: homeassistant.config_entries
Source: custom_components/myhome/gateway.py:152
Integration: MyHome (documentation, issues)
First occurred: 14:07:26 (1 occurrences)
Last logged: 14:07:26

Error setting up entry MyHomeServer1 Gateway for myhome
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 269, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/myhome/__init__.py", line 76, in async_setup_entry
    await myhome_gateway.connect()
  File "/config/custom_components/myhome/gateway.py", line 152, in connect
    await self.event_session.connect()
  File "/usr/local/lib/python3.8/site-packages/OWNd/connection.py", line 425, in connect
    await self._negotiate()
  File "/usr/local/lib/python3.8/site-packages/OWNd/connection.py", line 223, in _negotiate
    raw_response = await self._stream_reader.readuntil(OWNSession.SEPARATOR)
  File "/usr/local/lib/python3.8/asyncio/streams.py", line 629, in readuntil
    raise exceptions.IncompleteReadError(chunk, None)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of undefined expected bytes

Thanks,
Marcello

**Comment by anotherjulien** [comment]
Hi,

When did you update to 0.7.7?
Can you tell me which version of OWNd is required in your manifest.json file?

Thanks!

**Comment by monsterciattolo** [comment]
Ownd version 0.7.26

**Comment by anotherjulien** [comment]
Can you uninstall and reinstall version 0.7.7?
The OWNd dependency should be 0.7.27 (I removed version 0.7.26 because of a bug that is likely the cause of your problems)

**Comment by monsterciattolo** [comment]
i followed your suggestion and now integration seems loaded but covers don't work

Logger: homeassistant.helpers.service
Source: helpers/service.py:128 
First occurred: 18:00:30 (7 occurrences) 
Last logged: 21:30:58

Unable to find referenced entities cover.letto
Unable to find referenced entities cover.soggiorno_grande

this is my configuration that worked before latest upgrade

- platform: myhome
  devices:
    bagno_beige:
      where: '14'
      name: Tapparella Bagno Beige
      advanced: True
      manufacturer: Bticino
      model: H4661M2
    soggiorno_grande:
      where: '11'
      name: Tapparella Soggiorno Grande
      advanced: True
      manufacturer: Bticino
      model: H4661M2
    soggiorno_piccola:
      where: '12'
      name: Tapparella Soggiorno Piccola
      advanced: True
      manufacturer: Bticino
      model: H4661M2
    letto:
      where: '15'
      name: Tapparella Camera da letto
      advanced: True
      manufacturer: Bticino
      model: H4661M2
    cucina:
      where: '13'
      name: Tapparella Cucina
      advanced: True
      manufacturer: Bticino
      model: H4661M2
    cameretta:
      where: '16'
      name: Tapparella Cameretta
      advanced: True
      manufacturer: Bticino
      model: H4661M2

**Comment by anotherjulien** [comment]
I suppose you made no modification whatsoever in this configuration since it last worked?

Do you have any other debug logs that could help diagnosing the issue?

**Comment by monsterciattolo** [comment]
Correct, I didn't change anything.
Could you help to enable debug ?

**Comment by anotherjulien** [comment]
You can follow instructions [here](https://www.home-assistant.io/integrations/logger/) to set the default logs to `debug`.
This generates a lot of logs however, so start HA once with debug logs, collect them and then disable them and restart.

**Comment by monsterciattolo** [comment]
sorry for the delay.
i configured the debug option only for myhome component.

here some entries.

2021-06-07 13:47:37 DEBUG (MainThread) [custom_components.myhome] Negotiating test session.
2021-06-07 13:47:37 DEBUG (MainThread) [custom_components.myhome] Reply: *#*1##
2021-06-07 13:47:37 DEBUG (MainThread) [custom_components.myhome] Received SHA challenge: *98*2##
2021-06-07 13:47:37 DEBUG (MainThread) [custom_components.myhome] Detected SHA-256 method.
2021-06-07 13:47:37 DEBUG (MainThread) [custom_components.myhome] Accepting challenge, initiating handshake.
2021-06-07 13:47:38 DEBUG (MainThread) [custom_components.myhome] Received Ra.
2021-06-07 13:47:38 DEBUG (MainThread) [custom_components.myhome] Generated Rb.
2021-06-07 13:47:38 DEBUG (MainThread) [custom_components.myhome] Sending test session password.
2021-06-07 13:47:39 DEBUG (MainThread) [custom_components.myhome] Received HMAC response.
2021-06-07 13:47:39 DEBUG (MainThread) [custom_components.myhome] Server identity confirmed.
2021-06-07 13:47:39 INFO (MainThread) [custom_components.myhome] Test session closed.
2021-06-07 13:47:39 INFO (MainThread) [custom_components.myhome] Opening event session.
2021-06-07 13:47:41 DEBUG (MainThread) [custom_components.myhome] Negotiating event session.
2021-06-07 13:47:41 DEBUG (MainThread) [custom_components.myhome] Reply: *#*1##
2021-06-07 13:47:41 DEBUG (MainThread) [custom_components.myhome] Received SHA challenge: *98*2##
2021-06-07 13:47:41 DEBUG (MainThread) [custom_components.myhome] Detected SHA-256 method.
2021-06-07 13:47:41 DEBUG (MainThread) [custom_components.myhome] Accepting challenge, initiating handshake.

2021-06-07 13:48:07 DEBUG (MainThread) [custom_components.myhome] Received: *#13**15*200##
2021-06-07 13:48:07 INFO (MainThread) [custom_components.myhome] Gateway device type is: F454.
2021-06-07 13:48:32 DEBUG (MainThread) [custom_components.myhome] Received: *#13**15*200##
2021-06-07 13:48:32 INFO (MainThread) [custom_components.myhome] Gateway device type is: F454.
2021-06-07 13:48:57 DEBUG (MainThread) [custom_components.myhome] Received: *#13**15*200##
2021-06-07 13:48:57 INFO (MainThread) [custom_components.myhome] Gateway device type is: F454.
2021-06-07 13:48:58 INFO (MainThread) [custom_components.myhome] Found gateway: 192.168.188.13
2021-06-07 13:49:22 DEBUG (MainThread) [custom_components.myhome] Received: *#13**15*200##
2021-06-07 13:49:22 INFO (MainThread) [custom_components.myhome] Gateway device type is: F454.
2021-06-07 13:49:47 DEBUG (MainThread) [custom_components.myhome] Received: *#13**15*200##
2021-06-07 13:49:47 INFO (MainThread) [custom_components.myhome] Gateway device type is: F454.
2021-06-07 13:50:00 DEBUG (MainThread) [custom_components.myhome] Received: *#13**#1*01*07*06*2021##
2021-06-07 13:50:00 INFO (MainThread) [custom_components.myhome] Gateway broadcasting internal date: 2021-06-07.
2021-06-07 13:50:00 DEBUG (MainThread) [custom_components.myhome] Received: None
2021-06-07 13:50:00 INFO (MainThread) [custom_components.myhome] Received: None
2021-06-07 13:50:12 DEBUG (MainThread) [custom_components.myhome] Received: *#13**15*200##
2021-06-07 13:50:12 INFO (MainThread) [custom_components.myhome] Gateway device type is: F454.
2021-06-07 13:50:37 DEBUG (MainThread) [custom_components.myhome] Received: *#13**15*200##
2021-06-07 13:50:37 INFO (MainThread) [custom_components.myhome] Gateway device type is: F454.
2021-06-07 13:51:02 DEBUG (MainThread) [custom_components.myhome] Received: *#13**15*200##
2021-06-07 13:51:02 INFO (MainThread) [custom_components.myhome] Gateway device type is: F454.
2021-06-07 13:51:27 DEBUG (MainThread) [custom_components.myhome] Received: *#13**15*200##
2021-06-07 13:51:27 INFO (MainThread) [custom_components.myhome] Gateway device type is: F454.
2021-06-07 13:51:52 DEBUG (MainThread) [custom_components.myhome] Received: *#13**15*200##
2021-06-07 13:51:52 INFO (MainThread) [custom_components.myhome] Gateway device type is: F454.
2021-06-07 13:52:17 DEBUG (MainThread) [custom_components.myhome] Received: *#13**15*200##
2021-06-07 13:52:17 INFO (MainThread) [custom_components.myhome] Gateway device type is: F454.
2021-06-07 13:52:42 DEBUG (MainThread) [custom_components.myhome] Received: *#13**15*200##
2021-06-07 13:52:42 INFO (MainThread) [custom_components.myhome] Gateway device type is: F454.
2021-06-07 13:53:07 DEBUG (MainThread) [custom_components.myhome] Received: *#13**15*200##
2021-06-07 13:53:07 INFO (MainThread) [custom_components.myhome] Gateway device type is: F454.
2021-06-07 13:53:32 DEBUG (MainThread) [custom_components.myhome] Received: *#13**15*200##
2021-06-07 13:53:32 INFO (MainThread) [custom_components.myhome] Gateway device type is: F454.
2021-06-07 13:53:57 DEBUG (MainThread) [custom_components.myhome] Received: *#13**15*200##
2021-06-07 13:53:57 INFO (MainThread) [custom_components.myhome] Gateway device type is: F454.
2021-06-07 13:54:22 DEBUG (MainThread) [custom_components.myhome] Received: *#13**15*200##
2021-06-07 13:54:22 INFO (MainThread) [custom_components.myhome] Gateway device type is: F454.
2021-06-07 13:54:47 DEBUG (MainThread) [custom_components.myhome] Received: *#13**15*200##
2021-06-07 13:54:47 INFO (MainThread) [custom_components.myhome] Gateway device type is: F454.
2021-06-07 13:55:12 DEBUG (MainThread) [custom_components.myhome] Received: *#13**15*200##
2021-06-07 13:55:12 INFO (MainThread) [custom_components.myhome] Gateway device type is: F454.
2021-06-07 13:55:37 DEBUG (MainThread) [custom_components.myhome] Received: *#13**15*200##
2021-06-07 13:55:37 INFO (MainThread) [custom_components.myhome] Gateway device type is: F454.
2021-06-07 13:56:02 DEBUG (MainThread) [custom_components.myhome] Received: *#13**15*200##
2021-06-07 13:56:02 INFO (MainThread) [custom_components.myhome] Gateway device type is: F454.
2021-06-07 13:56:27 DEBUG (MainThread) [custom_components.myhome] Received: *#13**15*200##
2021-06-07 13:56:27 INFO (MainThread) [custom_components.myhome] Gateway device type is: F454.
2021-06-07 13:56:52 DEBUG (MainThread) [custom_components.myhome] Received: *#13**15*200##
2021-06-07 13:56:52 INFO (MainThread) [custom_components.myhome] Gateway device type is: F454.
2021-06-07 13:57:17 DEBUG (MainThread) [custom_components.myhome] Received: *#13**15*200##
2021-06-07 13:57:17 INFO (MainThread) [custom_components.myhome] Gateway device type is: F454.
2021-06-07 13:57:42 DEBUG (MainThread) [custom_components.myhome] Received: *#13**15*200##
2021-06-07 13:57:42 INFO (MainThread) [custom_components.myhome] Gateway device type is: F454.
2021-06-07 13:58:07 DEBUG (MainThread) [custom_components.myhome] Received: *#13**15*200##
2021-06-07 13:58:07 INFO (MainThread) [custom_components.myhome] Gateway device type is: F454.

When i try to open or close any cover i get nothings

2021-06-07 14:00:00 DEBUG (MainThread) [custom_components.myhome] Received: *#13**#1*01*07*06*2021##
2021-06-07 14:00:00 INFO (MainThread) [custom_components.myhome] Gateway broadcasting internal date: 2021-06-07.
2021-06-07 14:00:00 DEBUG (MainThread) [custom_components.myhome] Received: None
2021-06-07 14:00:00 INFO (MainThread) [custom_components.myhome] Received: None
2021-06-07 14:00:12 DEBUG (MainThread) [custom_components.myhome] Received: *#13**15*200##
2021-06-07 14:00:12 INFO (MainThread) [custom_components.myhome] Gateway device type is: F454.

**Comment by anotherjulien** [comment]
Quick question: when you go in the "developer tools" states part, what do you see in the cover entities?
For instance, instead of "cover.letto", do you see a "cover.tapparella_camera_da_letto"?

**Comment by monsterciattolo** [comment]
You are right....I changed the name on lovelace and now covers are working...thanks you so much!

**Comment by anotherjulien** [comment]
Would you by any chance have performed a fairly major Home-Assistant update recently?
