### ISSUE TITLE
Unable to connect to gateway F545

### ISSUE THREAD

**Issue by dinhchinh82** [anotherjulien/MyHOME#17]
hello,

I've installed the MyHome custom_component and trying to connect my F454 gateway.
By the way, I got unknow error and the log error as below:
I can make sure to input the correct password of the gateway. But I still confused that the gateway requires both username & password but in the configuration screen, only password is required.

> 2021-07-25 15:40:31 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 74, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 135, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 131, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 155, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 63, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 199, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 257, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/myhome/config_flow.py", line 265, in async_step_password
    return await self.async_step_test_connection()
  File "/config/custom_components/myhome/config_flow.py", line 197, in async_step_test_connection
    test_result = await test_session.test_connection()
  File "/usr/local/lib/python3.8/site-packages/OWNd/connection.py", line 184, in test_connection
    result = await self._negotiate()
  File "/usr/local/lib/python3.8/site-packages/OWNd/connection.py", line 292, in _negotiate
    hashedPass = f"*#{self._get_own_password(self._gateway.password, resulting_message.nonce)}##"
  File "/usr/local/lib/python3.8/site-packages/OWNd/connection.py", line 323, in _get_own_password
    password = int(password)
ValueError: invalid literal for int() with base 10: 'bticino'

Thank you so much for making this component.

**Comment by dinhchinh82** [comment]
I found the reason. I need to input the password to setup the iMyhome app, not the password for controllling.

**Comment by anotherjulien** [comment]
I'm not sure I understand which username and passwords you were referring to.
But I'm glad you worked it out :-)
