### ISSUE TITLE
Event session crashed.

### ISSUE THREAD

**Issue by stepir** [anotherjulien/MyHOME#26]
I have this happening every 30 mins - as a result the state of my entity is not properly reported. Anyone have any idea?

Thanks

```
This error originated from a custom integration.

Logger: custom_components.myhome
Source: /usr/local/lib/python3.9/site-packages/OWNd/connection.py:594 
Integration: MyHome (documentation, issues) 
First occurred: 9:10:38 PM (23 occurrences) 
Last logged: 9:57:08 PM

Event session crashed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/OWNd/connection.py", line 582, in get_next
    return OWNMessage.parse(data.decode())
  File "/usr/local/lib/python3.9/site-packages/OWNd/message.py", line 166, in parse
    return OWNEvent.parse(data)
  File "/usr/local/lib/python3.9/site-packages/OWNd/message.py", line 309, in parse
    return OWNAlarmEvent(data)
  File "/usr/local/lib/python3.9/site-packages/OWNd/message.py", line 952, in __init__
    self._sensor = int(self._where[1:])
ValueError: invalid literal for int() with base 10: ''
```

**Comment by anotherjulien** [comment]
Do you know what messages were received at this time by any chance?
It seems to be burglar alarm related messages, but I'm not sure which kind

**Comment by stepir** [comment]
how can I find? there's nothing nearby in the logs.

At the moment the only entities defined are 4 thermo and 3 switch so it must be one of those :-)

**Comment by anotherjulien** [comment]
The integration needs to parse ALL messages to know if it is destined for one of your configured entities, so it can be anything :-)
The best way would be to have an [OpenWebNet client](https://developer.legrand.com/documentation/client-download/) to capture all incoming messages; if it happens regularly every 30 minutes, you should be able to capture only a narrow timeframe of messages.

**Comment by stepir** [comment]
Thanks - for the moment it seems solved by just restarting HA every 4hrs! closing the issue. Tnx

**Comment by stepir** [comment]
now that I'm under debug I found:

```
2021-12-13 07:46:36 WARNING (MainThread) [custom_components.myhome] Unknown device: WHO=25 WHERE=32
2021-12-13 07:46:36 DEBUG (MainThread) [custom_components.myhome] Received: *1*1*17##
2021-12-13 07:46:36 INFO (MainThread) [custom_components.myhome] Light 17 is switched on.
2021-12-13 07:46:36 DEBUG (MainThread) [custom_components.myhome] Received: *1*0*#8##
2021-12-13 07:46:36 ERROR (MainThread) [custom_components.myhome] Event session crashed.
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/OWNd/connection.py", line 582, in get_next
return OWNMessage.parse(data.decode())
File "/usr/local/lib/python3.9/site-packages/OWNd/message.py", line 166, in parse
return OWNEvent.parse(data)
File "/usr/local/lib/python3.9/site-packages/OWNd/message.py", line 309, in parse
return OWNAlarmEvent(data)
File "/usr/local/lib/python3.9/site-packages/OWNd/message.py", line 956, in __init__
self._sensor = int(self._where[1:])
ValueError: invalid literal for int() with base 10: ''
2021-12-13 07:46:36 DEBUG (MainThread) [custom_components.myhome] Received: None
2021-12-13 07:46:36 WARNING (MainThread) [custom_components.myhome] Data received is not a message: None
2021-12-13 07:46:36 ERROR (MainThread) [custom_components.myhome] Event session crashed.
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/OWNd/connection.py", line 582, in get_next
return OWNMessage.parse(data.decode())
File "/usr/local/lib/python3.9/site-packages/OWNd/message.py", line 166, in parse
return OWNEvent.parse(data)
File "/usr/local/lib/python3.9/site-packages/OWNd/message.py", line 309, in parse
return OWNAlarmEvent(data)
File "/usr/local/lib/python3.9/site-packages/OWNd/message.py", line 956, in __init__
self._sensor = int(self._where[1:])
ValueError: invalid literal for int() with base 10: ''
2021-12-13 07:46:36 DEBUG (MainThread) [custom_components.myhome] Received: None
2021-12-13 07:46:36 WARNING (MainThread) [custom_components.myhome] Data received is not a message: None
2021-12-13 07:46:36 ERROR (MainThread) [custom_components.myhome] Event session crashed.
```

which seems to be the same issue of https://github.com/anotherjulien/MyHOME/issues/35
