### ISSUE TITLE
[Beta 0.9] Sensor Probe - Invalid WHERE length

### ISSUE THREAD

**Issue by caiosweet** [anotherjulien/MyHOME#74]
```
mh202n:
  mac: "00:03:00:xx:xx:xx"
  sensor:
    temperature_sensor:
      where: '105'
      name: Secondary sensor
      class: temperature
      manufacturer: BTicino
      model: L4692
```

```
Logger: homeassistant.config_entries
Source: custom_components/myhome/validate.py:115
Integration: MyHome (documentation, issues)
First occurred: 11:16:16 (1 occurrences)
Last logged: 11:16:16

Error setting up entry MH200N Gateway for myhome
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/myhome/__init__.py", line 47, in async_setup_entry
    _validated_config = config_schema(yaml.safe_load(await yaml_file.read()))
  File "/config/custom_components/myhome/validate.py", line 115, in __call__
    data = super().__call__(data)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 433, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: Invalid WHERE 105 length, it must be a string of 2 or 4 digits. for dictionary value @ data['mh202n']['sensor']['temperature_sensor']['where']

```

**Comment by anotherjulien** [comment]
hmmm, I didn't even think that outside WHO 1 and 2 the `where` can be a different length.
I'll add special cases in the config validator. I'll let you know when published!

**Comment by anotherjulien** [comment]
Should be OK with [227ef7b](https://github.com/anotherjulien/MyHOME/commit/227ef7b1d65baa7a0eeab168cd1e2bd8247f2aec)

**Comment by caiosweet** [comment]
I think it fixed the 4 digit PL switches status update as well.
