### ISSUE TITLE
[Beta 0.9] Climate - KeyError: 'fan'

### ISSUE THREAD

**Issue by caiosweet** [anotherjulien/MyHOME#75]
```
mh202n:
  mac: "00:03:00:xx:xx:xx"
  climate:
    termo_central_unit:
      zone: "#0"
      name: Termo Central unit
      heat: True
      cool: False
      standalone: False
      manufacturer: BTicino
      model: 3550
    termo_camera:
      zone: "1"
      name: Termo Camera
      heat: True
      cool: False
      standalone: False
      manufacturer: BTicino
      model: F430/4
    termo_studio:
      zone: "2"
      name: Termo Studio
      heat: True
      cool: False
      standalone: False
      manufacturer: BTicino
      model: F430/4
    termo_bagno:
      zone: "3"
      name: Termo Bagno
      heat: True
      cool: False
      standalone: False
      manufacturer: BTicino
      model: F430/4
    termo_sala:
      zone: "4"
      name: Termo Sala
      heat: True
      cool: False
      standalone: False
      manufacturer: BTicino
      model: F430/4
```

```
Logger: homeassistant.components.climate
Source: custom_components/myhome/climate.py:81
Integration: Termostato (documentation, issues)
First occurred: 11:20:41 (1 occurrences)
Last logged: 11:20:41

Error while setting up myhome platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/myhome/climate.py", line 81, in async_setup_entry
    fan=_configured_climate_devices[_climate_device][CONF_FAN_SUPPORT],
KeyError: 'fan'
```

**Comment by anotherjulien** [comment]
I've added fan back in the config validator, defaulting to false because it's not yet fully supported.
It should be fixed in [97d91bf](https://github.com/anotherjulien/MyHOME/commit/97d91bf59af9351f8fc8496b7e61f04084bd7ae3)
