### ISSUE TITLE
error with 0.9 and new configuration file

### ISSUE THREAD

**Issue by marcob79** [anotherjulien/MyHOME#78]
I just upgraded (before i build the new cfg file) and i got the following error

`This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/myhome/validate.py:174
Integration: MyHome (documentation, issues)
First occurred: 18:37:14 (1 occurrences)
Last logged: 18:37:14

Error setting up entry MH201 Gateway for myhome
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/myhome/__init__.py", line 51, in async_setup_entry
    _validated_config = config_schema(yaml.safe_load(await yaml_file.read()))
  File "/config/custom_components/myhome/validate.py", line 174, in __call__
    data = super().__call__(data)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 433, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: expected a dictionary for dictionary value @ data['mh201']['cover']
`

here the beginning of my cfgfile

mh201:
  mac: '00:03:50:A1:03:28'
  cover:
  general_shutter:
    where: '1'
    name: Generale
    advanced: False
    manufacturer: Bticino
    model: 4672
  living_shutter:
    where: '11'
    name: Sala piccola
    advanced: False
    manufacturer: Bticino
    model: 4672

**Comment by caiosweet** [comment]
Could it be an indentation problem? See [Sample-config](https://github.com/anotherjulien/MyHOME/wiki/Sample-config)

```
mh201:
  mac: "00:03:50:A1:03:28"
  cover:
    general_shutter::
      where: "1"
      name: Generale
      advanced: False
      manufacturer: BTicino
      model: 4672
  light:
    light1:
      etctecc
```

**Comment by marcob79** [comment]
You're right. 
Cover and general shutter where at the same level.
Sorry for that. 
Thanks
