### ISSUE TITLE
Error setting up gateway F454

### ISSUE THREAD

**Issue by SlevinK83** [anotherjulien/MyHOME#88]
Hi.

I am having a hard time integrating my myhomeserver1 (f454) into Home Assistant. I installed HACS and the myhome integration but it fails to establish a connection to the F454. Can someone help me? Its hard for me to interprete the error message.

```
Logger: homeassistant.config_entries
Source: custom_components/myhome/validate.py:177
Integration: MyHOME (documentation, issues)
First occurred: 13:40:26 (2 occurrences)
Last logged: 13:57:06

Error setting up entry F454 Gateway for myhome
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/myhome/__init__.py", line 51, in async_setup_entry
    _validated_config = config_schema(yaml.safe_load(await yaml_file.read()))
  File "/config/custom_components/myhome/validate.py", line 177, in __call__
    data = super().__call__(data)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 433, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: expected a dictionary for dictionary value @ data['f454']['light']
```

**Comment by CasaPetrillo** [comment]
Hi @SlevinK83!

I have the same problem with MH201 module after the latest updates.
Can you help me, please?

**Comment by SlevinK83** [comment]
Sorry. To long ago but what I do know is that it worked at the end 🤷‍♂️ i think a reset of the MH201 did the job.

**Comment by CasaPetrillo** [comment]
Hi @SlevinK83!
Thanks for reply!
How can I reset the MH201?
